package com.weaponanimationreplacer;

import com.google.common.collect.ImmutableSet;
import static com.weaponanimationreplacer.Swap.AnimationType.ROTATE;
import static com.weaponanimationreplacer.Swap.AnimationType.SHUFFLE_LEFT;
import static com.weaponanimationreplacer.Swap.AnimationType.SHUFFLE_RIGHT;
import static com.weaponanimationreplacer.Swap.AnimationType.STAND;
import static com.weaponanimationreplacer.Swap.AnimationType.WALK_BACKWARD;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Value;
import net.runelite.api.Actor;
import net.runelite.api.ItemID;
import net.runelite.api.kit.KitType;

public class Constants
{
	public static final Set<Integer> JAW_SLOT = ImmutableSet.of(10556, 10557, 10558, 10559, 10567, 20802, 22308, 22309, 22310, 22311, 22312, 22313, 22314, 22315, 22337, 22338, 22339, 22340, 22341, 22342, 22343, 22344, 22345, 22346, 22347, 22348, 22349, 22721, 22722, 22723, 22724, 22725, 22726, 22727, 22728, 22729, 22730, 23460, 23461, 23462, 23463, 23464, 23465, 23466, 23467, 23468, 23469, 23470, 23471, 23472, 23473, 23474, 23475, 23476, 23477, 23478, 23479, 23480, 23481, 23482, 23483, 23484, 23485, 23486, 25228, 25229, 25230, 25231, 25232, 25233, 25234, 25235, 25236, 25237, 25238, 25239, 25240, 25241, 25242, 25243, 25212, 25213, 25214, 25215, 25216, 25217, 25218, 25219, 25220, 25221, 25222, 25223, 25224, 25225, 25226, 25227);

	// key is item id, value is the slot id it should go in.
	public static final Map<Integer, KitType> EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT = new HashMap<>();
	static {
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(19724, KitType.JAW); // Longbow (u)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(48, KitType.WEAPON); // Longbow (u)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(50, KitType.WEAPON); // Shortbow (u)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(54, KitType.WEAPON); // Oak shortbow (u)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(56, KitType.WEAPON); // Oak longbow (u)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(58, KitType.WEAPON); // Willow longbow (u)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(60, KitType.WEAPON); // Willow shortbow (u)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(62, KitType.WEAPON); // Maple longbow (u)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(64, KitType.WEAPON); // Maple shortbow (u)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(66, KitType.WEAPON); // Yew longbow (u)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(68, KitType.WEAPON); // Yew shortbow (u)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(70, KitType.WEAPON); // Magic longbow (u)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(72, KitType.WEAPON); // Magic shortbow (u)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(229, KitType.WEAPON); // Vial
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(272, KitType.SHIELD); // Fish food
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(301, KitType.WEAPON); // Lobster pot
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(303, KitType.WEAPON); // Small fishing net
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(305, KitType.WEAPON); // Big fishing net
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(307, KitType.WEAPON); // Fishing rod
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(309, KitType.WEAPON); // Fly fishing rod
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(311, KitType.WEAPON); // Harpoon
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(314, KitType.WEAPON); // Feather
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(411, KitType.SHIELD); // Oyster pearl (dupe of 413)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(413, KitType.SHIELD); // Oyster pearls
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(421, KitType.AMULET); // Lathas' amulet
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(583, KitType.WEAPON); // Bailing bucket (icon empty, appears empty)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(585, KitType.WEAPON); // Bailing bucket (icon full, appears empty)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(590, KitType.WEAPON); // Tinderbox
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(675, KitType.WEAPON); // Rock pick
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(677, KitType.WEAPON); // Panning tray
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(717, KitType.SHIELD); // Scrawled note
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(718, KitType.SHIELD); // A scribbled note
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(719, KitType.SHIELD); // Scrumpled note
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(727, KitType.WEAPON); // Hollow reed (dupe of 1785)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(728, KitType.WEAPON); // Hollow reed (dupe of 1785)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(731, KitType.WEAPON); // Enchanted vial
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(740, KitType.HEAD); // Blue hat
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(796, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(797, KitType.SHIELD); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(798, KitType.WEAPON); // null (item icon is invisible)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(945, KitType.WEAPON); // Throwing rope
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(946, KitType.WEAPON); // Knife
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(952, KitType.WEAPON); // Spade
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(954, KitType.WEAPON); // Rope
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(970, KitType.SHIELD); // Papyrus
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(972, KitType.SHIELD); // Papyrus (dupe of 970)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(973, KitType.WEAPON); // Charcoal
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(1511, KitType.SHIELD); // Logs
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(1601, KitType.WEAPON); // Diamond
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(1603, KitType.WEAPON); // Ruby
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(1605, KitType.WEAPON); // Emerald
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(1607, KitType.WEAPON); // Sapphire
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(1609, KitType.WEAPON); // Opal
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(1611, KitType.WEAPON); // Jade
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(1613, KitType.WEAPON); // Red topaz
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(1615, KitType.WEAPON); // Dragonstone
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(1733, KitType.WEAPON); // Needle
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(1735, KitType.WEAPON); // Shears
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(1741, KitType.SHIELD); // Leather
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(1761, KitType.SHIELD); // Soft clay
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(1785, KitType.WEAPON); // Glassblowing pipe
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(1917, KitType.WEAPON); // Beer
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(1919, KitType.WEAPON); // Beer glass
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(1925, KitType.WEAPON); // Bucket
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(1931, KitType.WEAPON); // Pot
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(1963, KitType.WEAPON); // Banana
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(1973, KitType.SHIELD); // Chocolate bar
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(2347, KitType.WEAPON); // Hammer
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(2395, KitType.WEAPON); // Magic ogre potion
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(2422, KitType.HEAD); // Blue partyhat
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(2480, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(2520, KitType.WEAPON); // Brown toy horsey
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(2522, KitType.WEAPON); // White toy horsey
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(2524, KitType.WEAPON); // Black toy horsey
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(2526, KitType.WEAPON); // Grey toy horsey
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(2888, KitType.WEAPON); // A stone bowl
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(2889, KitType.WEAPON); // A stone bowl
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(2946, KitType.WEAPON); // Golden tinderbox
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(2949, KitType.WEAPON); // Golden hammer
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(2968, KitType.SHIELD); // Druidic spell
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(2969, KitType.SHIELD); // A used spell (dupe of 2968)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(3080, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(3157, KitType.WEAPON); // Karambwan vessel
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(3159, KitType.WEAPON); // Karambwan vessel (dupe of 3157)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(3164, KitType.SHIELD); // Karamjan rum
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(3177, KitType.SHIELD); // Left-handed banana
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(3688, KitType.WEAPON); // Unstrung lyre
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(3711, KitType.WEAPON); // Keg of beer
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(3801, KitType.WEAPON); // Keg of beer (dupe of 3711)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(3803, KitType.WEAPON); // Beer tankard
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(3850, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(3893, KitType.WEAPON); // Stool
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(3935, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(3937, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(3939, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(3941, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(3943, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(3945, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(3947, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(3949, KitType.WEAPON); // null
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(3953, KitType.WEAPON); // null (lyre but held in a weird way)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(3969, KitType.WEAPON); // null (dragon harpoon but floating)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(3971, KitType.WEAPON); // null (infernal harpoon but floating)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4032, KitType.WEAPON); // null
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4073, KitType.WEAPON); // Damp tinderbox (dupe of 590)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4080, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4085, KitType.SHIELD); // Wax
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4155, KitType.WEAPON); // Enchanted gem
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4159, KitType.WEAPON); // Leaf-bladed spear (dupe of regular leaf-bladed spear)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4161, KitType.WEAPON); // Bag of salt
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4162, KitType.WEAPON); // Rock hammer
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4193, KitType.WEAPON); // Extended brush
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4212, KitType.WEAPON); // New crystal bow
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4213, KitType.WEAPON); // New crystal bow
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4214, KitType.WEAPON); // Crystal bow full
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4215, KitType.WEAPON); // Crystal bow 9/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4216, KitType.WEAPON); // Crystal bow 8/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4217, KitType.WEAPON); // Crystal bow 7/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4218, KitType.WEAPON); // Crystal bow 6/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4219, KitType.WEAPON); // Crystal bow 5/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4220, KitType.WEAPON); // Crystal bow 4/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4221, KitType.WEAPON); // Crystal bow 3/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4222, KitType.WEAPON); // Crystal bow 2/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4223, KitType.WEAPON); // Crystal bow 1/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4224, KitType.WEAPON); // New crystal shield
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4225, KitType.WEAPON); // Crystal shield full
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4226, KitType.WEAPON); // Crystal shield 9/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4227, KitType.WEAPON); // Crystal shield 8/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4228, KitType.WEAPON); // Crystal shield 7/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4229, KitType.WEAPON); // Crystal shield 6/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4230, KitType.WEAPON); // Crystal shield 5/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4231, KitType.WEAPON); // Crystal shield 4/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4232, KitType.WEAPON); // Crystal shield 3/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4233, KitType.WEAPON); // Crystal shield 2/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4234, KitType.WEAPON); // Crystal shield 1/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4235, KitType.WEAPON); // New crystal shield
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4251, KitType.WEAPON); // Ectophial
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4435, KitType.SHIELD); // Weather report
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4498, KitType.WEAPON); // Rope
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4500, KitType.WEAPON); // Pole
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4501, KitType.WEAPON); // Null (dupe of 4500)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4605, KitType.WEAPON); // Snake charm
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4613, KitType.WEAPON); // Spinning plate
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4614, KitType.WEAPON); // Broken plate
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4692, KitType.SHIELD); // Gold leaf
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4704, KitType.WEAPON); // Stone bowl
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4705, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4809, KitType.SHIELD); // Torn page
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4814, KitType.SHIELD); // Sithik portrait
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4815, KitType.SHIELD); // Sithik portrait (dupe of 4814)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4816, KitType.SHIELD); // Signed portrait (dupe of 4814)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4817, KitType.SHIELD); // Book of portraiture
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4829, KitType.SHIELD); // Book of 'h.a.m'
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(4837, KitType.SHIELD); // Necromancy book
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(5060, KitType.WEAPON); // Dwarven battleaxe
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(5061, KitType.WEAPON); // Dwarven battleaxe
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(5081, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(5083, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(5325, KitType.WEAPON); // Gardening trowel
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(5329, KitType.WEAPON); // Secateurs
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(5331, KitType.WEAPON); // Watering can
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(5333, KitType.WEAPON); // Watering can(1)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(5334, KitType.WEAPON); // Watering can(2)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(5335, KitType.WEAPON); // Watering can(3)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(5336, KitType.WEAPON); // Watering can(4)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(5337, KitType.WEAPON); // Watering can(5)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(5338, KitType.WEAPON); // Watering can(6)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(5339, KitType.WEAPON); // Watering can(7)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(5340, KitType.WEAPON); // Watering can(8)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(5341, KitType.WEAPON); // Rake
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(5343, KitType.WEAPON); // Seed dibber
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(5350, KitType.WEAPON); // Empty plant pot
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(5560, KitType.WEAPON); // Stethoscope
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(5561, KitType.WEAPON); // Mystic jewel
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(5603, KitType.WEAPON); // Shears (dupe of 1735)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(5614, KitType.WEAPON); // Magic carpet
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(5732, KitType.WEAPON); // Stool
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(5769, KitType.SHIELD); // Calquat keg
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(5771, KitType.WEAPON); // Dwarven stout(1)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(5982, KitType.SHIELD); // Watermelon
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6036, KitType.WEAPON); // Plant cure
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6209, KitType.WEAPON); // Small fishing net
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6281, KitType.SHIELD); // Thatch spar light
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6283, KitType.SHIELD); // Thatch spar med (dupe)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6285, KitType.SHIELD); // Thatch spar dense (dupe)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6448, KitType.WEAPON); // Spadeful of coke
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6449, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6451, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6468, KitType.WEAPON); // Plant cure
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6470, KitType.WEAPON); // Compost potion(4)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6472, KitType.WEAPON); // Compost potion(3) (dupe)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6474, KitType.WEAPON); // Compost potion(2) (dupe)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6476, KitType.WEAPON); // Compost potion(1) (dupe)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6565, KitType.WEAPON); // null (item icon is invisible)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6573, KitType.WEAPON); // Onyx
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6635, KitType.WEAPON); // Commorb
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6657, KitType.WEAPON); // Camo top
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6658, KitType.WEAPON); // Camo bottoms
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6659, KitType.WEAPON); // Camo helmet
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6664, KitType.WEAPON); // Fishing explosive
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6670, KitType.WEAPON); // Fishbowl
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6671, KitType.WEAPON); // Fishbowl
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6672, KitType.WEAPON); // Fishbowl
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6673, KitType.WEAPON); // Fishbowl and net
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6713, KitType.WEAPON); // Wrench
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6714, KitType.WEAPON); // Holy wrench
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6721, KitType.WEAPON); // Rusty scimitar
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6722, KitType.WEAPON); // Zombie head
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6748, KitType.WEAPON); // Demonic sigil
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6772, KitType.SHIELD); // Smouldering pot
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6788, KitType.SHIELD); // Torn robe
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6789, KitType.SHIELD); // Torn robe
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6817, KitType.WEAPON); // Slender blade
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6818, KitType.WEAPON); // Bow-sword
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(6864, KitType.WEAPON); // Marionette handle
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7004, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7118, KitType.SHIELD); // Canister
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7119, KitType.SHIELD); // Cannon ball
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7120, KitType.SHIELD); // Ramrod
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7121, KitType.SHIELD); // Repair plank
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7404, KitType.SHIELD); // Red logs
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7405, KitType.SHIELD); // Green logs
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7406, KitType.SHIELD); // Blue logs
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7410, KitType.WEAPON); // Queen's secateurs
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7412, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7421, KitType.WEAPON); // Fungicide spray 10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7422, KitType.WEAPON); // Fungicide spray 9
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7423, KitType.WEAPON); // Fungicide spray 8
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7424, KitType.WEAPON); // Fungicide spray 7
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7425, KitType.WEAPON); // Fungicide spray 6
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7426, KitType.WEAPON); // Fungicide spray 5
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7427, KitType.WEAPON); // Fungicide spray 4
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7428, KitType.WEAPON); // Fungicide spray 3
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7429, KitType.WEAPON); // Fungicide spray 2
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7430, KitType.WEAPON); // Fungicide spray 1
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7431, KitType.WEAPON); // Fungicide spray 0
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7475, KitType.WEAPON); // Brulee
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7509, KitType.WEAPON); // Dwarven rock cake
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7572, KitType.SHIELD); // Red banana
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7637, KitType.WEAPON); // Silvthrill rod
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7682, KitType.WEAPON); // Hoop
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7684, KitType.WEAPON); // Dart
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7686, KitType.WEAPON); // Bow and arrow
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7688, KitType.WEAPON); // Kettle
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7690, KitType.WEAPON); // Full kettle
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7691, KitType.WEAPON); // Hot kettle
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7728, KitType.WEAPON); // Empty cup
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7730, KitType.WEAPON); // Cup of tea
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7731, KitType.WEAPON); // Cup of tea
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7732, KitType.WEAPON); // Porcelain cup
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7733, KitType.WEAPON); // Cup of tea
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7734, KitType.WEAPON); // Cup of tea
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7735, KitType.WEAPON); // Porcelain cup
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7736, KitType.WEAPON); // Cup of tea
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7737, KitType.WEAPON); // Cup of tea
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7740, KitType.WEAPON); // Beer
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7742, KitType.WEAPON); // Beer glass
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7744, KitType.WEAPON); // Asgarnian ale
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7746, KitType.WEAPON); // Greenman's ale
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7748, KitType.WEAPON); // Dragon bitter
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7750, KitType.WEAPON); // Moonlight mead
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7752, KitType.WEAPON); // Cider
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7754, KitType.WEAPON); // Chef's delight
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7756, KitType.WEAPON); // Paintbrush
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7758, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7773, KitType.WEAPON); // Branch
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7777, KitType.WEAPON); // Long vine
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(7778, KitType.WEAPON); // Short vine
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8794, KitType.WEAPON); // Saw
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8798, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8799, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8800, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8801, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8802, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8803, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8804, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8805, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8806, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8807, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8808, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8809, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8810, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8811, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8812, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8813, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8814, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8815, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8816, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8817, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8818, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8819, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8820, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8821, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8822, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8823, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8824, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8825, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8826, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8827, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8829, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8830, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8831, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8832, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8833, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8834, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8835, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8857, KitType.WEAPON); // Shot
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8858, KitType.WEAPON); // 18lb shot
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8859, KitType.WEAPON); // 22lb shot
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8940, KitType.SHIELD); // Rum
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8941, KitType.SHIELD); // Rum
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8986, KitType.WEAPON); // Bucket
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(8987, KitType.WEAPON); // Torch
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9020, KitType.WEAPON); // Queen's secateurs
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9060, KitType.SHIELD); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9061, KitType.SHIELD); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9062, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9063, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9065, KitType.SHIELD); // Emerald lantern
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9085, KitType.SHIELD); // Empty vial
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9086, KitType.SHIELD); // Vial of water
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9087, KitType.SHIELD); // Waking sleep vial
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9088, KitType.SHIELD); // Guam vial
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9089, KitType.SHIELD); // Marr vial
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9090, KitType.SHIELD); // Guam-marr vial
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9103, KitType.HEAD); // A special tiara
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9138, KitType.SHIELD); // null (logs)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9420, KitType.SHIELD); // Bronze limbs
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9422, KitType.SHIELD); // Blurite limbs
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9423, KitType.SHIELD); // Iron limbs
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9425, KitType.SHIELD); // Steel limbs
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9427, KitType.SHIELD); // Mithril limbs
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9429, KitType.SHIELD); // Adamantite limbs
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9431, KitType.SHIELD); // Runite limbs
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9440, KitType.WEAPON); // Wooden stock
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9442, KitType.WEAPON); // Oak stock
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9444, KitType.WEAPON); // Willow stock
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9446, KitType.WEAPON); // Teak stock
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9448, KitType.WEAPON); // Maple stock
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9450, KitType.WEAPON); // Mahogany stock
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9452, KitType.WEAPON); // Yew stock
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9454, KitType.WEAPON); // Bronze crossbow (u)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9456, KitType.WEAPON); // Blurite crossbow (u)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9457, KitType.WEAPON); // Iron crossbow (u)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9459, KitType.WEAPON); // Steel crossbow (u)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9461, KitType.WEAPON); // Mithril crossbow (u)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9463, KitType.WEAPON); // Adamant crossbow (u)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9465, KitType.WEAPON); // Runite crossbow (u)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9590, KitType.WEAPON); // Dossier
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9631, KitType.SHIELD); // null (bucket)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9646, KitType.SHIELD); // Castle sketch 1
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9647, KitType.SHIELD); // Castle sketch 2
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9648, KitType.SHIELD); // Castle sketch 3
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9660, KitType.WEAPON); // Bucket
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9665, KitType.WEAPON); // Torch
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9681, KitType.WEAPON); // Commorb v2
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9893, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9894, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9895, KitType.SHIELD); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9896, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9897, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9898, KitType.SHIELD); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9899, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9905, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9906, KitType.WEAPON); // Ghost buster 500
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9907, KitType.WEAPON); // Ghost buster 500
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9908, KitType.WEAPON); // Ghost buster 500
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9909, KitType.WEAPON); // Ghost buster 500
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9910, KitType.WEAPON); // Ghost buster 500
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9911, KitType.WEAPON); // Ghost buster 500
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9912, KitType.WEAPON); // Ghost buster 500
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9913, KitType.SHIELD); // White destabiliser
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9914, KitType.SHIELD); // Red destabiliser
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9915, KitType.SHIELD); // Blue destabiliser
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9916, KitType.SHIELD); // Green destabiliser
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9917, KitType.SHIELD); // Yellow destabiliser
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9918, KitType.SHIELD); // Black destabiliser
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9926, KitType.SHIELD); // null (dupe destabilizer)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9927, KitType.SHIELD); // null (dupe destabilizer)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9928, KitType.SHIELD); // null (dupe destabilizer)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9929, KitType.SHIELD); // null (dupe destabilizer)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9930, KitType.SHIELD); // null (dupe destabilizer)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9931, KitType.SHIELD); // null (dupe destabilizer)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(9943, KitType.WEAPON); // Sandbag
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(10022, KitType.SHIELD); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(10029, KitType.WEAPON); // Teasing stick
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(10131, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(10152, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(10153, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(10154, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(10155, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(10164, KitType.WEAPON); // null (rope)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(10484, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(10485, KitType.WEAPON); // Scroll
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(10488, KitType.SHIELD); // Selected iron
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(10544, KitType.WEAPON); // Healing vial(2)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(10566, KitType.CAPE); // Fire cape
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(10568, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(10810, KitType.SHIELD); // Arctic pine logs
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(10841, KitType.WEAPON); // Apricot cream pie
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(10842, KitType.WEAPON); // Decapitated head
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(10857, KitType.WEAPON); // Severed leg
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(10860, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(10861, KitType.SHIELD); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(10886, KitType.WEAPON); // Prayer book
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(10952, KitType.WEAPON); // Slayer bell
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11012, KitType.WEAPON); // Wand
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11013, KitType.WEAPON); // Infused wand
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11027, KitType.WEAPON); // Easter egg
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11028, KitType.WEAPON); // Easter egg
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11029, KitType.WEAPON); // Easter egg
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11030, KitType.WEAPON); // Easter egg
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11046, KitType.WEAPON); // Rope
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11063, KitType.WEAPON); // null
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11068, KitType.WEAPON); // Gold bracelet
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11071, KitType.WEAPON); // Sapphire bracelet
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11078, KitType.WEAPON); // Emerald bracelet
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11087, KitType.WEAPON); // Ruby bracelet
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11094, KitType.WEAPON); // Diamond bracelet
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11117, KitType.WEAPON); // Dragon bracelet
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11132, KitType.WEAPON); // Onyx bracelet
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11151, KitType.SHIELD); // Dream vial (empty)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11152, KitType.SHIELD); // Dream vial (water)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11153, KitType.SHIELD); // Dream vial (herb)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11154, KitType.WEAPON); // Dream potion
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11204, KitType.WEAPON); // Shrink-me-quick
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11279, KitType.WEAPON); // Elvarg's head
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11288, KitType.SHIELD); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11289, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11290, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11291, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11292, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11293, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11294, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11295, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11296, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11297, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11298, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11299, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11300, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11301, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11302, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11303, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11304, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11305, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11306, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11307, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11308, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11309, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11310, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11311, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11312, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11313, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11314, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11315, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11316, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11317, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11318, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11319, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11320, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11321, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11322, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11323, KitType.WEAPON); // Barbarian rod
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11542, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11543, KitType.WEAPON); // null
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11748, KitType.WEAPON); // New crystal bow (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11749, KitType.WEAPON); // Crystal bow full (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11750, KitType.WEAPON); // Crystal bow 9/10 (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11751, KitType.WEAPON); // Crystal bow 8/10 (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11752, KitType.WEAPON); // Crystal bow 7/10 (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11753, KitType.WEAPON); // Crystal bow 6/10 (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11754, KitType.WEAPON); // Crystal bow 5/10 (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11755, KitType.WEAPON); // Crystal bow 4/10 (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11756, KitType.WEAPON); // Crystal bow 3/10 (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11757, KitType.WEAPON); // Crystal bow 2/10 (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11758, KitType.WEAPON); // Crystal bow 1/10 (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11759, KitType.WEAPON); // New crystal shield (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11760, KitType.WEAPON); // Crystal shield full (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11761, KitType.WEAPON); // Crystal shield 9/10 (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11762, KitType.WEAPON); // Crystal shield 8/10 (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11763, KitType.WEAPON); // Crystal shield 7/10 (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11764, KitType.WEAPON); // Crystal shield 6/10 (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11765, KitType.WEAPON); // Crystal shield 5/10 (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11766, KitType.WEAPON); // Crystal shield 4/10 (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11767, KitType.WEAPON); // Crystal shield 3/10 (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11768, KitType.WEAPON); // Crystal shield 2/10 (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(11769, KitType.WEAPON); // Crystal shield 1/10 (i)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12401, KitType.WEAPON); // null
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12660, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12661, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12662, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12663, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12664, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12665, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12666, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12667, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12668, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12669, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12670, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12671, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12672, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12673, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12674, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12676, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12677, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12678, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12679, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12680, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12681, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12682, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12683, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12684, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12685, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12686, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12687, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12688, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12689, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(12690, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13080, KitType.WEAPON); // New crystal halberd full (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13081, KitType.WEAPON); // Crystal halberd full (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13082, KitType.WEAPON); // Crystal halberd 9/10 (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13083, KitType.WEAPON); // Crystal halberd 8/10 (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13084, KitType.WEAPON); // Crystal halberd 7/10 (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13085, KitType.WEAPON); // Crystal halberd 6/10 (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13086, KitType.WEAPON); // Crystal halberd 5/10 (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13087, KitType.WEAPON); // Crystal halberd 4/10 (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13088, KitType.WEAPON); // Crystal halberd 3/10 (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13089, KitType.WEAPON); // Crystal halberd 2/10 (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13090, KitType.WEAPON); // Crystal halberd 1/10 (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13091, KitType.WEAPON); // New crystal halberd full
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13092, KitType.WEAPON); // Crystal halberd full
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13093, KitType.WEAPON); // Crystal halberd 9/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13094, KitType.WEAPON); // Crystal halberd 8/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13095, KitType.WEAPON); // Crystal halberd 7/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13096, KitType.WEAPON); // Crystal halberd 6/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13097, KitType.WEAPON); // Crystal halberd 5/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13098, KitType.WEAPON); // Crystal halberd 4/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13099, KitType.WEAPON); // Crystal halberd 3/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13100, KitType.WEAPON); // Crystal halberd 2/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13101, KitType.WEAPON); // Crystal halberd 1/10
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13188, KitType.WEAPON); // Diango's claws
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13215, KitType.WEAPON); // Tiger toy
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13216, KitType.WEAPON); // Lion toy
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13217, KitType.WEAPON); // Snow leopard toy
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13218, KitType.WEAPON); // Amur leopard toy
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13233, KitType.SHIELD); // Smouldering stone
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13353, KitType.WEAPON); // Gricoller's can
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13446, KitType.WEAPON); // Dark essence block
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13570, KitType.WEAPON); // Juniper charcoal
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13682, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13683, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(13685, KitType.WEAPON); // null
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(16888, KitType.WEAPON); // New crystal bow
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(16889, KitType.WEAPON); // New crystal bow (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(16890, KitType.WEAPON); // New crystal shield
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(16891, KitType.WEAPON); // New crystal shield (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(16892, KitType.WEAPON); // New crystal halberd full (i)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(16893, KitType.WEAPON); // New crystal halberd full
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(19492, KitType.WEAPON); // Zenyte bracelet
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(19493, KitType.WEAPON); // Zenyte
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(19560, KitType.WEAPON); // Charged onyx
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(19562, KitType.WEAPON); // Deconstructed onyx
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20275, KitType.WEAPON); // Gnomish firelighter
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20278, KitType.WEAPON); // Gnomish firelighter
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20397, KitType.WEAPON); // Spear
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20401, KitType.WEAPON); // Yew shortbow
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20402, KitType.WEAPON); // Rune scimitar
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20403, KitType.WEAPON); // Maple shortbow
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20406, KitType.WEAPON); // Dragon scimitar
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20415, KitType.WEAPON); // Adamant platebody
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20416, KitType.WEAPON); // Adamant platelegs
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20417, KitType.WEAPON); // Blue d'hide body
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20418, KitType.WEAPON); // Blue d'hide chaps
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20421, KitType.WEAPON); // Rune platebody
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20424, KitType.WEAPON); // Black d'hide chaps
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20428, KitType.WEAPON); // Dragon chainbody
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20429, KitType.WEAPON); // Dragon platelegs
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20431, KitType.WEAPON); // Ancient staff
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20552, KitType.WEAPON); // Rune battleaxe
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20553, KitType.WEAPON); // Beginner wand
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20554, KitType.WEAPON); // Toktz-xil-ak
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20555, KitType.WEAPON); // Rune 2h sword
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20556, KitType.WEAPON); // Apprentice wand
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20558, KitType.WEAPON); // Magic shortbow
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20559, KitType.WEAPON); // Dragon 2h sword
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20560, KitType.WEAPON); // Master wand
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20561, KitType.WEAPON); // Adamant full helm
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20562, KitType.WEAPON); // Mystic hat
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20563, KitType.WEAPON); // Proselyte sallet
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20564, KitType.WEAPON); // Proselyte hauberk
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20565, KitType.WEAPON); // Proselyte cuisse
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20566, KitType.WEAPON); // Red d'hide body
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20567, KitType.WEAPON); // Red d'hide chaps
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20568, KitType.WEAPON); // Splitbark helm
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20571, KitType.WEAPON); // Warrior helm
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20572, KitType.WEAPON); // Archer helm
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20573, KitType.WEAPON); // Farseer helm
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20574, KitType.WEAPON); // Infinity top
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20575, KitType.WEAPON); // Infinity bottoms
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20576, KitType.WEAPON); // 3rd age robe top
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20577, KitType.WEAPON); // 3rd age robe
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20579, KitType.WEAPON); // Mystic boots
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20580, KitType.WEAPON); // Snakeskin boots
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20581, KitType.WEAPON); // Mithril gloves
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20583, KitType.WEAPON); // Rune gloves
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20584, KitType.WEAPON); // Amulet of accuracy
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20587, KitType.WEAPON); // Rope
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20695, KitType.SHIELD); // Bruma root
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20696, KitType.SHIELD); // Bruma kindling
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20781, KitType.WEAPON); // Killer's knife
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(20785, KitType.WEAPON); // Dragon warhammer
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21186, KitType.CAPE); // Fire max cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21205, KitType.WEAPON); // Elder maul
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21206, KitType.WEAPON); // Dragon sword
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21207, KitType.WEAPON); // Dragon thrownaxe
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21253, KitType.WEAPON); // Farmer's strawhat
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21254, KitType.WEAPON); // Farmer's strawhat
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21261, KitType.WEAPON); // Mysterious orb
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21270, KitType.WEAPON); // Eternal gem
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21284, KitType.CAPE); // Infernal max cape
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21297, KitType.CAPE); // Infernal cape
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21347, KitType.WEAPON); // Amethyst
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21396, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21397, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21398, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21399, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21400, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21401, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21402, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21403, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21404, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21405, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21406, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21407, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21408, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21409, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21410, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21411, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21412, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21413, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21414, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21415, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21416, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21417, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21418, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21419, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21420, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21421, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21422, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21423, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21424, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21425, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21426, KitType.WEAPON); // Clan wars cape
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21427, KitType.WEAPON); // Clan wars cape
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21652, KitType.WEAPON); // Drift net
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21655, KitType.WEAPON); // Pufferfish
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21722, KitType.HEAD); // Diving helmet
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21723, KitType.CAPE); // Diving apparatus
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21918, KitType.SHIELD); // Dragon limbs
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21921, KitType.WEAPON); // Dragon crossbow (u)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(21952, KitType.WEAPON); // Magic stock
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(22688, KitType.WEAPON); // Null
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(22691, KitType.WEAPON); // Null
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(22694, KitType.WEAPON); // Null
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(22697, KitType.WEAPON); // Null
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(22700, KitType.WEAPON); // Null
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(22994, KitType.WEAPON); // Bottomless compost bucket
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(22997, KitType.WEAPON); // Bottomless compost bucket
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(23609, KitType.WEAPON); // Ava's accumulator
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(23679, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(23684, KitType.WEAPON); // null
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(23766, KitType.WEAPON); // null
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(23767, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(23819, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(23839, KitType.WEAPON); // Vial
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(23879, KitType.WEAPON); // Vial
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24077, KitType.SHIELD); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24078, KitType.SHIELD); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24079, KitType.SHIELD); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24080, KitType.SHIELD); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24081, KitType.SHIELD); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24082, KitType.SHIELD); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24083, KitType.SHIELD); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24084, KitType.SHIELD); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24085, KitType.SHIELD); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24086, KitType.SHIELD); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24087, KitType.SHIELD); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24088, KitType.SHIELD); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24089, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24090, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24091, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24092, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24093, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24094, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24095, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24096, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24097, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24098, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24099, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24100, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24101, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24102, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24103, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24104, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24105, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24106, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24107, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24108, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24109, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24110, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24111, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24112, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24113, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24114, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24115, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24116, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24117, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24118, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24119, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24120, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24121, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24122, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24273, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24274, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24275, KitType.WEAPON); // null
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24300, KitType.WEAPON); // Spooky hood
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24301, KitType.WEAPON); // Spooky robe
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24302, KitType.WEAPON); // Spooky skirt
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24303, KitType.WEAPON); // Spooky gloves
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24304, KitType.WEAPON); // Spooky boots
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24386, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24435, KitType.WEAPON); // Festive pot
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24437, KitType.SHIELD); // Gingerbread shield
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24438, KitType.SHIELD); // Iced gingerbread shield
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24439, KitType.SHIELD); // Iced gingerbread shield
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24440, KitType.SHIELD); // Iced gingerbread shield
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24460, KitType.WEAPON); // Twisted teleport scroll
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24487, KitType.SHIELD); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24790, KitType.WEAPON); // Long rope
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24998, KitType.SHIELD); // null (item icon is invisible)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(24999, KitType.SHIELD); // null (item icon is invisible)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25000, KitType.WEAPON); // null (item icon is invisible)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25062, KitType.WEAPON); // null
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25087, KitType.WEAPON); // Trailblazer teleport scroll
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25102, KitType.SHIELD); // Fairy mushroom
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25110, KitType.WEAPON); // Trailblazer axe
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25112, KitType.WEAPON); // Trailblazer pickaxe
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25114, KitType.WEAPON); // Trailblazer harpoon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25116, KitType.WEAPON); // null
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25375, KitType.WEAPON); // null
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25484, KitType.WEAPON); // Toxic blowpipe (beta - bronze)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25485, KitType.WEAPON); // Toxic blowpipe (beta - iron)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25486, KitType.WEAPON); // Toxic blowpipe (beta - steel)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25487, KitType.WEAPON); // Toxic blowpipe (beta - black)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25488, KitType.WEAPON); // Toxic blowpipe (beta - mithril)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25489, KitType.WEAPON); // Toxic blowpipe (beta - adamant)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25490, KitType.WEAPON); // Toxic blowpipe (beta - rune)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25491, KitType.WEAPON); // Toxic blowpipe (beta - dragon)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25492, KitType.WEAPON); // Black d'hide body (beta)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25493, KitType.WEAPON); // Black d'hide chaps (beta)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25494, KitType.WEAPON); // Black d'hide vambraces (beta)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25495, KitType.WEAPON); // Crystal helm (beta)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25496, KitType.WEAPON); // Crystal body (beta)
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25497, KitType.WEAPON); // Crystal legs (beta)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25615, KitType.WEAPON); // Large water container
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25633, KitType.WEAPON); // Imcando hammer (broken)
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25710, KitType.WEAPON); // Stool
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25711, KitType.WEAPON); // Stool
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25848, KitType.WEAPON); // null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25938, KitType.WEAPON); // Anim offhand
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25939, KitType.WEAPON); // Null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25941, KitType.WEAPON); // Anim offhand
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25942, KitType.WEAPON); // Null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25944, KitType.WEAPON); // Anim offhand
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25945, KitType.WEAPON); // Null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25947, KitType.WEAPON); // Anim offhand
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25948, KitType.WEAPON); // Null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25950, KitType.WEAPON); // Anim offhand
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25951, KitType.WEAPON); // Null
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25953, KitType.WEAPON); // Anim offhand
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(25954, KitType.WEAPON); // Null
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26184, KitType.WEAPON); // Blue icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26185, KitType.WEAPON); // Blue icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26186, KitType.WEAPON); // Blue icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26187, KitType.WEAPON); // Blue icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26188, KitType.WEAPON); // Blue icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26189, KitType.WEAPON); // Blue icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26190, KitType.WEAPON); // Blue icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26191, KitType.WEAPON); // Blue icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26192, KitType.WEAPON); // Blue icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26193, KitType.WEAPON); // Blue icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26194, KitType.WEAPON); // Blue icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26195, KitType.WEAPON); // Blue icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26196, KitType.WEAPON); // Blue icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26197, KitType.WEAPON); // Blue icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26198, KitType.WEAPON); // Blue icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26199, KitType.WEAPON); // Blue icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26200, KitType.WEAPON); // Red icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26201, KitType.WEAPON); // Red icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26202, KitType.WEAPON); // Red icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26203, KitType.WEAPON); // Red icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26204, KitType.WEAPON); // Red icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26205, KitType.WEAPON); // Red icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26206, KitType.WEAPON); // Red icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26207, KitType.WEAPON); // Red icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26208, KitType.WEAPON); // Red icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26209, KitType.WEAPON); // Red icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26210, KitType.WEAPON); // Red icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26211, KitType.WEAPON); // Red icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26212, KitType.WEAPON); // Red icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26213, KitType.WEAPON); // Red icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26214, KitType.WEAPON); // Red icon
//		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26215, KitType.WEAPON); // Red icon
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26374, KitType.WEAPON); // Zaryte crossbow
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26382, KitType.HEAD); // Torva full helm
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26384, KitType.TORSO); // Torva platebody
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT.put(26386, KitType.LEGS); // Torva platelegs
	}
	@Value
	public static class NameAndIconId {
		String name;
		int iconId;

		public String name(String actualName) {
			if (name == null) {
				return actualName;
			} else {
				return name;
			}
		}

		public int iconId(int actualIconId) {
			if (iconId == -1) {
				return actualIconId;
			} else {
				return iconId;
			}
		}
	}
	public static final Map<Integer, NameAndIconId> EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES = new HashMap<>();
	static {
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(796, new NameAndIconId("Exploding vial", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(797, new NameAndIconId("Mortar (Pestle and mortar)", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(798, new NameAndIconId("Pestle (Pestle and mortar)", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(2480, new NameAndIconId("Hammer", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(3080, new NameAndIconId("Infernal pickaxe (yellow)", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(3850, new NameAndIconId("Open book (green)", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(3935, new NameAndIconId("Bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(3937, new NameAndIconId("Bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(3939, new NameAndIconId("Bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(3941, new NameAndIconId("Bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(3943, new NameAndIconId("Bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(3945, new NameAndIconId("Bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(3947, new NameAndIconId("Bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(3949, new NameAndIconId("Bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(4032, new NameAndIconId("Mod ash's mug", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(4080, new NameAndIconId("Yoyo", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(4705, new NameAndIconId("Open book (red/yellow)", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(5081, new NameAndIconId("Dragon pickaxe (yellow)", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(5083, new NameAndIconId("Dragon pickaxe (or) (yellow)", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(6565, new NameAndIconId("Bob the cat", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(7004, new NameAndIconId("Chisel", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(7412, new NameAndIconId("Bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(7758, new NameAndIconId("Rusty sword (looks weird)", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8798, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8799, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8800, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8801, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8802, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8803, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8804, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8805, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8806, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8807, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8808, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8809, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8810, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8811, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8812, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8813, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8814, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8815, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8816, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8817, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8818, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8819, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8820, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8821, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8822, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8823, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8824, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8825, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8826, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8827, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8829, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8830, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8831, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8832, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8833, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8834, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(8835, new NameAndIconId("Chair/bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(9060, new NameAndIconId("Red bottle (offhand)", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(9061, new NameAndIconId("Blue bottle (offhand)", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(9062, new NameAndIconId("Blue bottle", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(9063, new NameAndIconId("Yellow bottle", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(9893, new NameAndIconId("Mortar (Pestle and mortar)", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(9894, new NameAndIconId("Hammer", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(9895, new NameAndIconId("Chisel (offhand)", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(9896, new NameAndIconId("Frying pan", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(9897, new NameAndIconId("Axe", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(9898, new NameAndIconId("Red shield", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(9899, new NameAndIconId("Small red shield", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(9905, new NameAndIconId("Barrel", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(10131, new NameAndIconId("Barb-tail harpoon (held backwards)", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(10152, new NameAndIconId("Brown barb-tail kebbit in noose", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(10153, new NameAndIconId("White barb-tail kebbit in noose", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(10154, new NameAndIconId("Beige barb-tail kebbit in noose", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(10155, new NameAndIconId("Dark brown barb-tail kebbit in noose", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(10484, new NameAndIconId("Brown spiky kebbit in noose", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(10566, new NameAndIconId("Fire cape (untextured)", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(10568, new NameAndIconId("3rd age pickaxe (light)", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(10860, new NameAndIconId("Tea flask", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(10861, new NameAndIconId("Tiny tea cup", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11063, new NameAndIconId("Paintbrush (I think)", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11288, new NameAndIconId("Yellow vial (offhand)", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11289, new NameAndIconId("Yellow vial", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11290, new NameAndIconId("Cyan vial", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11291, new NameAndIconId("Red vial", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11292, new NameAndIconId("Lime green vial", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11293, new NameAndIconId("Light turquoise vial", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11294, new NameAndIconId("Blue vial", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11295, new NameAndIconId("Dark gray vial", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11296, new NameAndIconId("White vial", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11297, new NameAndIconId("Orange vial", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11298, new NameAndIconId("Light lime green vial", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11299, new NameAndIconId("Pink vial", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11300, new NameAndIconId("Light blue vial", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11301, new NameAndIconId("Light green vial", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11302, new NameAndIconId("Purple vial", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11303, new NameAndIconId("Light orange vial", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11304, new NameAndIconId("Turquoise vial", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11305, new NameAndIconId("Black vial", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11306, new NameAndIconId("Training bow (held incorrectly)", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11307, new NameAndIconId("Shortbow (held incorrectly", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11308, new NameAndIconId("Oak Shortbow (held incorrectly", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11309, new NameAndIconId("Willow Shortbow (held incorrectly", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11310, new NameAndIconId("Maple Shortbow (held incorrectly", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11311, new NameAndIconId("Yew Shortbow (held incorrectly", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11312, new NameAndIconId("Magic Shortbow (held incorrectly", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11313, new NameAndIconId("Longbow (held incorrectly", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11314, new NameAndIconId("Oak Longbow (held incorrectly", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11315, new NameAndIconId("Willow Longbow (held incorrectly", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11316, new NameAndIconId("Maple Longbow (held incorrectly", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11317, new NameAndIconId("Yew Longbow (held incorrectly", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11318, new NameAndIconId("Magic Longbow (held incorrectly", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11319, new NameAndIconId("Seercull (held incorrectly)", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11320, new NameAndIconId("Shark", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11321, new NameAndIconId("Swordfish", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11322, new NameAndIconId("Tuna", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11542, new NameAndIconId("Stool", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(11543, new NameAndIconId("Bench", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(12401, new NameAndIconId("Map (buggy graphic)", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(13682, new NameAndIconId("Cabbage", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(13683, new NameAndIconId("Cabbage", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(13685, new NameAndIconId("Red cabbage", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(21186, new NameAndIconId("Fire max cape (untextured)", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(21284, new NameAndIconId("Infernal max cape (untextured)", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(21297, new NameAndIconId("Infernal cape (untextured)", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(23679, new NameAndIconId("Dragon pickaxe (zalcano) (yellow)", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(23684, new NameAndIconId("Crystal pickaxe (glowing)", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(23819, new NameAndIconId("Orb of light", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24077, new NameAndIconId("Bolt tip", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24078, new NameAndIconId("Bolt tip", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24079, new NameAndIconId("Bolt tip", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24080, new NameAndIconId("Bolt tip", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24081, new NameAndIconId("Bolt tip", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24082, new NameAndIconId("Bolt tip", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24083, new NameAndIconId("Bolt tip", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24084, new NameAndIconId("Bolt tip", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24085, new NameAndIconId("Bolt tip", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24086, new NameAndIconId("Bolt tip", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24087, new NameAndIconId("Bolt tip", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24088, new NameAndIconId("Bolt tip", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24089, new NameAndIconId("Bolt", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24090, new NameAndIconId("Bolt", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24091, new NameAndIconId("Bolt", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24092, new NameAndIconId("Bolt", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24093, new NameAndIconId("Bolt", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24094, new NameAndIconId("Bolt", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24095, new NameAndIconId("Bolt", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24096, new NameAndIconId("Bolt", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24097, new NameAndIconId("Bolt", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24098, new NameAndIconId("Bolt", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24099, new NameAndIconId("Bolt", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24100, new NameAndIconId("Bolt", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24101, new NameAndIconId("Bolt", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24102, new NameAndIconId("Bolt", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24103, new NameAndIconId("Bolt", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24104, new NameAndIconId("Bolt", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24105, new NameAndIconId("Bolt", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24106, new NameAndIconId("Headless arrow", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24107, new NameAndIconId("Arrow shaft", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24108, new NameAndIconId("Arrowhead", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24109, new NameAndIconId("Arrowhead", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24110, new NameAndIconId("Arrowhead", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24111, new NameAndIconId("Arrowhead", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24112, new NameAndIconId("Arrowhead", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24113, new NameAndIconId("Arrowhead", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24114, new NameAndIconId("Arrowhead", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24115, new NameAndIconId("Arrowhead", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24116, new NameAndIconId("Dart tip", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24117, new NameAndIconId("Dart tip", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24118, new NameAndIconId("Dart tip", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24119, new NameAndIconId("Dart tip", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24120, new NameAndIconId("Dart tip", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24121, new NameAndIconId("Dart tip", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24122, new NameAndIconId("Dart tip", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24273, new NameAndIconId("Basilisk stone prison", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24274, new NameAndIconId("Basilisk stone prison", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24275, new NameAndIconId("Basilisk stone prison", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24386, new NameAndIconId("Green and brown stick", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24487, new NameAndIconId("Sextant", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24998, new NameAndIconId("Black crystal", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(24999, new NameAndIconId("Stick", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(25000, new NameAndIconId("Paper", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(25848, new NameAndIconId("Amethyst dart tip", -1));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(25938, new NameAndIconId("Ghommal's hilt 1 (mainhand)", 25926));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(25941, new NameAndIconId("Ghommal's hilt 2 (mainhand)", 25928));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(25944, new NameAndIconId("Ghommal's hilt 3 (mainhand)", 25930));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(25947, new NameAndIconId("Ghommal's hilt 4 (mainhand)", 25932));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(25950, new NameAndIconId("Ghommal's hilt 5 (mainhand)", 25934));
		EQUIPPABLE_ITEMS_NOT_MARKED_AS_EQUIPMENT_NAMES.put(25953, new NameAndIconId("Ghommal's hilt 6 (mainhand)", 25936));
	}

	public static final Set<Integer> showSleeves = new HashSet<>();

	public static Constants.NegativeId mapNegativeId(int id) {
		if (id == -1) return new Constants.NegativeId(Constants.NegativeIdsMap.NULL, -1);
		else if (id <= -2 && id > -2 - KitType.values().length) {
			return new Constants.NegativeId(Constants.NegativeIdsMap.HIDE_SLOT, id * -1 - 2);
		}
		else if (id == -14) {
			return new Constants.NegativeId(Constants.NegativeIdsMap.SHOW_SLOT, KitType.ARMS.getIndex());
		}
		else if (id == -15) {
			return new Constants.NegativeId(Constants.NegativeIdsMap.SHOW_SLOT, KitType.HAIR.getIndex());
		}
		else if (id == -16) {
			return new Constants.NegativeId(Constants.NegativeIdsMap.SHOW_SLOT, KitType.JAW.getIndex());
		}
		throw new IllegalArgumentException();
	}

	public static int mapNegativeId(Constants.NegativeId id) {
		if (id.type == Constants.NegativeIdsMap.NULL) return -1;
		else if (id.type == Constants.NegativeIdsMap.HIDE_SLOT) {
			return -2 - id.id;
		}
		else if (id.type == Constants.NegativeIdsMap.SHOW_SLOT) {
			if (id.id == KitType.ARMS.getIndex()) {
				return -14;
			}
			else if (id.id == KitType.HAIR.getIndex()) {
				return -15;
			}
			else if (id.id == KitType.JAW.getIndex()) {
				return -16;
			}
		}
		throw new IllegalArgumentException();
	}

	@RequiredArgsConstructor
	public enum HiddenSlot {
		HEAD(KitType.HEAD, ItemID.IRON_MED_HELM, "Hide helm"),
		CAPE(KitType.CAPE, 3779, "Hide cape"),
		AMULET(KitType.AMULET, 1796, "Hide amulet"),
		WEAPON(KitType.WEAPON, ItemID.SHADOW_SWORD, "Hide weapon"),
		TORSO(KitType.TORSO, ItemID.GHOSTLY_ROBE, "Hide torso"),
		SHIELD(KitType.SHIELD, ItemID.IRON_SQ_SHIELD, "Hide off hand"),
		ARMS(KitType.ARMS, ItemID.EXPEDITIOUS_BRACELET, "Hide sleeves"),
		LEGS(KitType.LEGS, ItemID.GHOSTLY_ROBE_6108, "Hide legs"),
		HAIR(KitType.HAIR, 2421, "Hide hair"),
		HANDS(KitType.HANDS, 21736, "Hide hands"),
		BOOTS(KitType.BOOTS, ItemID.IRON_BOOTS, "Hide boots"),
		JAW(KitType.JAW, 4593, "Hide jaw"),
		;

		final KitType kitType;
		final int iconIdToShow;
		public final String actionName;
	}

	@RequiredArgsConstructor
	public enum ShownSlot {
		HEAD(KitType.HEAD, ItemID.IRON_MED_HELM),
		CAPE(KitType.CAPE, 3779),
		AMULET(KitType.AMULET, 1796),
		WEAPON(KitType.WEAPON, ItemID.SHADOW_SWORD),
		TORSO(KitType.TORSO, ItemID.GHOSTLY_ROBE),
		SHIELD(KitType.SHIELD, ItemID.IRON_SQ_SHIELD),
		ARMS(KitType.ARMS, ItemID.GOLD_BRACELET),
		LEGS(KitType.LEGS, ItemID.GHOSTLY_ROBE_6108),
		HAIR(KitType.HAIR, 2419),
		HANDS(KitType.HANDS, 21736),
		BOOTS(KitType.BOOTS, ItemID.IRON_BOOTS),
		JAW(KitType.JAW, ItemID.BASILISK_JAW),
		;

		final KitType kitType;
		final int iconIdToShow;
	}

	public enum ActorAnimation
	{
		IDLE(Actor::getIdlePoseAnimation, Actor::setIdlePoseAnimation, STAND),
		IDLE_ROTATE_LEFT(Actor::getIdleRotateLeft, Actor::setIdleRotateLeft, ROTATE),
		IDLE_ROTATE_RIGHT(Actor::getIdleRotateRight, Actor::setIdleRotateRight, ROTATE),
		WALK(Actor::getWalkAnimation, Actor::setWalkAnimation, Swap.AnimationType.WALK),
		WALK_ROTATE_180(Actor::getWalkRotate180, Actor::setWalkRotate180, WALK_BACKWARD),
		WALK_ROTATE_LEFT(Actor::getWalkRotateLeft, Actor::setWalkRotateLeft, SHUFFLE_LEFT),
		WALK_ROTATE_RIGHT(Actor::getWalkRotateRight, Actor::setWalkRotateRight, SHUFFLE_RIGHT),
		RUN(Actor::getRunAnimation, Actor::setRunAnimation, Swap.AnimationType.RUN),
		;

		interface AnimationGetter
		{
			int getAnimation(Actor a);
		}

		interface AnimationSetter
		{
			void setAnimation(Actor a, int animationId);
		}

		@Getter
		private final Swap.AnimationType type;
		private final AnimationGetter animationGetter;
		private final AnimationSetter animationSetter;

		ActorAnimation(AnimationGetter animationGetter, AnimationSetter animationSetter, Swap.AnimationType type)
		{
			this.type = type;
			this.animationGetter = animationGetter;
			this.animationSetter = animationSetter;
		}

		public int getAnimation(Actor actor)
		{
			return animationGetter.getAnimation(actor);
		}

		public void setAnimation(Actor actor, int animationId)
		{
			animationSetter.setAnimation(actor, animationId);
		}
	}

	public enum NegativeIdsMap {
		NULL,
		HIDE_SLOT,
		SHOW_SLOT,
//		SLEEVES,
//		HAIR,
//		JAW,
		;
	}

	@RequiredArgsConstructor
		public static final class NegativeId {
		public final NegativeIdsMap type;
		public final int id;
	}
}
